// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyasagnvogvcoxxrzgzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5YXNhZ252b2d2Y294eHJ6Z3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NzQ5NDYsImV4cCI6MjA2NjU1MDk0Nn0.6wrdYfeO3QYsMYRszEmMQHjfgzxAGXMStrpUrx5oQkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);